name: chatbot
description: SKmagic Chatbot
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  json_annotation: ^4.8.1
  firebase_core: ^2.15.0
  cloud_firestore_odm: ^1.0.0-dev.64
  device_info_plus: ^9.0.3
  firebase_database: ^10.2.4
  cloud_firestore: ^4.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  copy_with_extension_gen: ^5.0.2
  cloud_firestore_odm_generator: ^1.0.0-dev.64

flutter:
  uses-material-design: true
